<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Tablita', 'doctrine');

/**
 * BaseTablita
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $a
 * @property integer $b
 * 
 * @method integer getId() Returns the current record's "id" value
 * @method integer getA()  Returns the current record's "a" value
 * @method integer getB()  Returns the current record's "b" value
 * @method Tablita setId() Sets the current record's "id" value
 * @method Tablita setA()  Sets the current record's "a" value
 * @method Tablita setB()  Sets the current record's "b" value
 * 
 * @package    jobeet
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTablita extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('tablita');
        $this->hasColumn('id', 'integer', 8, array(
             'type' => 'integer',
             'autoincrement' => true,
             'primary' => true,
             'length' => 8,
             ));
        $this->hasColumn('a', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('b', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}